-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMDB0ltYWdlSWQFUHJpY2UNU29ydE9yZGVyUGFnZQABAgAAAQIADKMAAADiAAMAbwEEADABAJYAAAAAjAH0ATABACQBAAAAbwEFADABAOgCAAAAggACAAYDAQMCAwMFAwABAgIAAOBIiVDgQQIAAAAAAADgvwABAAEYAAABAAABAAABAAAAAQAAAAAA

-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2026-04-18 23:37:46
-- Luau version 6, Types version 3
-- Time taken: 0.000310 seconds

return {
    ImageId = 2189707847;
    Price = 500;
    SortOrderPage = -0.5;
}