-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMKBVNvdW5kBkNvbG9yMwdmcm9tUkdCC0NvbG9yTm9ybWFsCUNvbG9ySGVhdAdNYXhIZWF0BkRhbWFnZQtCdWxsZXRTcGVlZAhGaXJlRnJlcRRJZ25vcmVWZXJpZnlGaXJlRnJlcQABBQAAAQIAJ6MAAAD/AAQAAAAAAP8BAAAAAAAAMAEAbgAAAACkAQMAAAgQgIwCYACMA3UAjAR/AJ8BBAIwAQDlBAAAAKQBAwAACBCAjAL/AIwDFACMBBQAnwEEAjABAFAFAAAAjAEDADABAAcGAAAAjAEPADABAA8HAAAAjAGwBDABAKUIAAAAjAFkADABAEAJAAAAqQEBADABAGwKAAAAggACAAsDAQMCAwMEAAgQgAMEAwUDBgMHAwgDCQMKAAEAARgAAAABAAAAAQAAAAAAAAABAAAAAAAAAAEAAAEAAAEAAAEAAAEAAAIBAAAAAABBhNPaXvM7JLA06OBfntDyMZzErnNAuds=

-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2026-04-18 23:37:57
-- Luau version 6, Types version 3
-- Time taken: 0.000734 seconds

return {
    Sound = {};
    ColorNormal = Color3.fromRGB(96, 117, 127);
    ColorHeat = Color3.fromRGB(255, 20, 20);
    MaxHeat = 3;
    Damage = 15;
    BulletSpeed = 1200;
    FireFreq = 100;
    IgnoreVerifyFireFreq = true;
}