-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMDBU1vZGVsB1Nwb2lsZXIORmluZEZpcnN0Q2hpbGQAAgUBAAAAAAdNAQA7AAAAAG8EAQC8AgEDAgAAAJ8CAwCCAgAAAwMBAwIDAwABAAEYAAABAAAAAAIAAAAAAQAAAQIAA6MAAADAAAAAggACAAEGAAEAAQABGAAAAAEAAAAAAQ==

-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2026-04-18 23:36:49
-- Luau version 6, Types version 3
-- Time taken: 0.000497 seconds

return function(arg1) -- Line 1
    return arg1.Model:FindFirstChild("Spoiler")
end