-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMLBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplGUJBVFRMRV9TRVJWRVJfU0VSVkVSX1RZUEUVU0VSVkVSX1RZUEVfQVRUUl9OQU1FDEJhdHRsZVNlcnZlchFQcml2YXRlU2VydmVyVHlwZQABBQAAAQIAGaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0CAKEGAAAATQICGAcAAACfAQICTQIBAAgAAADiAwsAbwQMADAEA5cJAAAAbwQNADAEA2YKAAAAnwICAIICAAAOAwEEAAAAQAMCAwMDBAQAAEBAAwUDBgMHAwgDCQUCCQoDCgMLAAEAARgAAAAAAAAAAQAAAAAAAAEAAAEAAAIAAP0AAQAAAAAAVwchHU/5hLB+vDRVt9PG8icfNmllw0sc

-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2026-04-18 23:45:15
-- Luau version 6, Types version 3
-- Time taken: 0.000593 seconds

return require(game:GetService("ReplicatedStorage").Std.TableUtils).requireValidIndexAndFreeze({
    BATTLE_SERVER_SERVER_TYPE = "BattleServer";
    SERVER_TYPE_ATTR_NAME = "PrivateServerType";
})