-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMJBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlDk1hbnNpb25Sb2JiZXJ5FE1hbnNpb25Sb2JiZXJ5QmluZGVyBVN0YXJ0DUJvc3NOUENCaW5kZXIPTGFzZXJUcmFwQmluZGVyAAEFAAABAgAmowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQIA8wYAAABNAgKFBwAAAJ8BAgK8AgEcCAAAAJ8CAgGkAgUAAABAQE0DAPMGAAAATQMDdwkAAACfAgICvAICHAgAAACfAgIBpAIFAAAAQEBNAwDzBgAAAE0DA+kKAAAAnwICArwDAhwIAAAAnwMCAYIAAQALAwEEAAAAQAMCAwMDBAQAAEBAAwUDBgMHAwgDCQABAAEYAAAAAAAAAAEAAAAAAAABAAABAAAAAAAAAAAAAQAAAAAAAAEAAAEBAAAAAACAs8epyrVEhNHdpPexuLGr8KvQ3bJ3rag=

-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2026-04-18 23:29:44
-- Luau version 6, Types version 3
-- Time taken: 0.000461 seconds

local ReplicatedStorage = game:GetService("ReplicatedStorage")
require(ReplicatedStorage.MansionRobbery.MansionRobberyBinder):Start()
require(ReplicatedStorage.MansionRobbery.BossNPCBinder):Start()
require(ReplicatedStorage.MansionRobbery.LaserTrapBinder):Start()