-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMEB3JlcXVpcmUGc2NyaXB0BlBhcmVudAdFelV0aWxzAAECAAABAgALowAAAKQAAQAAAABApAEDAAAAIEBNAQEkBAAAAE0BAcIFAAAAnwACAIIAAAAGAwEEAAAAQAMCBAAAIEADAwMEAAEAARgAAQAAAAAAAAAAAAEAAAAAAA==

-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2026-04-18 23:41:55
-- Luau version 6, Types version 3
-- Time taken: 0.000358 seconds

return require(script.Parent.EzUtils)