-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMHEWNvbmRpdGlvbkZ1bmN0aW9uBENtZHIEVXRpbAxNYWtlRW51bVR5cGURQ29uZGl0aW9uRnVuY3Rpb24Kc3RhcnRzV2l0aAxSZWdpc3RlclR5cGUAAggBAAAAABJvAwAATQQAngEAAABNBASeAgAAAE0EBLIDAAAAbwUEAP8GAAABAAAAbwcFAMUGBwIBAAAAnwQDALwBAN0GAAAAnwEAAYIAAQAHAwEDAgMDAwQDBQMGAwcAAQABGAAAAAAAAAAAAAAAAAAAAAAAAQIAAAAAAQAAAQIAA6MAAADAAAAAggACAAEGAAEAAQABGAAAAAEAAAAAAQ==

-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2026-04-18 23:33:44
-- Luau version 6, Types version 3
-- Time taken: 0.000659 seconds

return function(arg1) -- Line 1
    arg1:RegisterType("conditionFunction", arg1.Cmdr.Util.MakeEnumType("ConditionFunction", {"startsWith"}))
end