-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMMBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplCFRBR19OQU1FDlJBTktfQVRUUl9OQU1FEFVQREFURV9GUkVRVUVOQ1kLVG9wQ3Jld0ZsYWcIQ3Jld1JhbmsAAQUAAAECAByjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAgChBgAAAE0CAhgHAAAAnwECAk0CAQAIAAAA4gMMAG8EDQAwBAO0CQAAAG8EDgAwBAPHCgAAAIwEHgAwBAOkCwAAAJ8CAgCCAgAADwMBBAAAAEADAgMDAwQEAABAQAMFAwYDBwMIAwkDCgUDCQoLAwsDDAABAAEYAAAAAAAAAAEAAAAAAAABAAABAAABAAABAAD9AAEAAAAAAKlePX8VUOjOZyepjJWi/lvZRioLm5pXfg==

-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2026-04-18 23:47:07
-- Luau version 6, Types version 3
-- Time taken: 0.000472 seconds

return require(game:GetService("ReplicatedStorage").Std.TableUtils).requireValidIndexAndFreeze({
    TAG_NAME = "TopCrewFlag";
    RANK_ATTR_NAME = "CrewRank";
    UPDATE_FREQUENCY = 30;
})