-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMJB0VsZW1lbnQIRnJhZ21lbnQIZWxlbWVudHMOY3JlYXRlRnJhZ21lbnQHcmVxdWlyZQZzY3JpcHQGUGFyZW50C0VsZW1lbnRLaW5kBFR5cGUAAgUBAgAABQACAA8PD/8BAwAAAAAA+wIAAPsEAABNAwSXAAAAAGoDAQL7AgEA+wQBAE0DBCkBAAAAagMBAjAAAcICAAAAggECAAMDAQMCAwMABAQBGAAAAQAAAAABAAAAAAEAAAUAAAAABQAAAQIPAAADDwABFg8BCg0PAhMEF6MAAACkAAEAAAAAQKQDAwAAACBATQIDJAQAAABNAQJ6BQAAAJ8AAgKkAQEAAAAAQKQEAwAAACBATQMEJAQAAABNAgMRBgAAAJ8BAgLAAgcAEgABABIAAACCAgIACAMFBAAAAEADBgQAACBAAwcDCAMJBgABAAEAARgAAAAAAAAAAAAAAQAAAAAAAAAAAgAACAEAAAAAAfqj92tayfmryGed/xhLyxKeBjyQ+PQU7onvic+dhOV/1lSwKbbJi08=

local v0 = require(script.Parent.ElementKind);
local v1 = require(script.Parent.Type);
return function(v2) --[[ Line: 4 ]] --[[ Name: createFragment ]]
    -- upvalues: v1 (copy), v0 (copy)
    return {
        [v1] = v1.Element, 
        [v0] = v0.Fragment, 
        elements = v2
    };
end;