-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMBJWhleSB0aGVyZSEgbmljZSB0byBtZWV0IHlvdSA6KSAtYmFkY2MAAQEAAAECAAOjAAAAbwAAAIIAAgABAwEAAQABGAABAAEAAAAAAA==

-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2026-04-18 23:43:52
-- Luau version 6, Types version 3
-- Time taken: 0.000240 seconds

return "hey there! nice to meet you :) -badcc"