-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMCClNka1ZlcnNpb24FMi4yLjMAAQIAAAECAAajAAAA4gABAG8BAgAwAQA3AAAAAIIAAgADAwEFAQADAgABAAEYAAABAAADAQAAAAAA

-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2026-04-18 23:30:11
-- Luau version 6, Types version 3
-- Time taken: 0.000275 seconds

return {
    SdkVersion = "2.2.3";
}