-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMIBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlCk5ldE9ialBvb2wQTmV0T2JqUG9vbEJpbmRlcgVTdGFydBROZXRPYmpQb29sSXRlbUJpbmRlcgABBQAAAQIAHKMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0CAIwGAAAATQICdAcAAACfAQICvAIBHAgAAACfAgIBpAIFAAAAQEBNAwCMBgAAAE0DA5oJAAAAnwICArwDAhwIAAAAnwMCAYIAAQAKAwEEAAAAQAMCAwMDBAQAAEBAAwUDBgMHAwgAAQABGAAAAAAAAAABAAAAAAAAAQAAAQAAAAAAAAEAAAEBAAAAAACVW3B08qAJTmvxLiTP+fe65UNnAKefGnU=

-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2026-04-18 23:29:46
-- Luau version 6, Types version 3
-- Time taken: 0.000536 seconds

local ReplicatedStorage = game:GetService("ReplicatedStorage")
require(ReplicatedStorage.NetObjPool.NetObjPoolBinder):Start()
require(ReplicatedStorage.NetObjPool.NetObjPoolItemBinder):Start()