-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMLBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZAZFbnVtZXIGQ29tbW9uBFJhcmUJVWx0cmFSYXJlBEVwaWMJTGVnZW5kYXJ5AAEJAAABAgAaowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQIAoQYAAABNAgJXBwAAAJ8BAgJSAgEA/wMAAAUAAABvBAgAbwUJAG8GCgBvBwsAbwgMAMUDBAYBAAAAnwICAIICAAANAwEEAAAAQAMCAwMDBAQAAEBAAwUDBgMHAwgDCQMKAwsAAQABGAAAAAAAAAABAAAAAAAAAgAAAQEBAQEAAPsAAQAAAAAAcj4t/831T4v+ae2X2vSh4QImOotA+kf+

-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2026-04-18 23:45:24
-- Luau version 6, Types version 3
-- Time taken: 0.000605 seconds

return require(game:GetService("ReplicatedStorage").Std.Enumer)({"Common", "Rare", "UltraRare", "Epic", "Legendary"})