-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMLBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplEVBPT0xfT0JKX1BUUl9OQU1FD0FDVElWRV9PQkpfTkFNRRhOZXRPYmpQb29sSXRlbVBvb2xPYmpQdHIMTmV0T2JqQWN0aXZlAAEFAAABAgAZowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQIAoQYAAABNAgIYBwAAAJ8BAgJNAgEACAAAAOIDCwBvBAwAMAQD2wkAAABvBA0AMAQD7AoAAACfAgIAggIAAA4DAQQAAABAAwIDAwMEBAAAQEADBQMGAwcDCAMJBQIJCgMKAwsAAQABGAAAAAAAAAABAAAAAAAAAQAAAQAAAQAA/gABAAAAAACOOXmkn2RQhz8Av28aRqhz/iFu0Lz9E6U=

-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2026-04-18 23:44:19
-- Luau version 6, Types version 3
-- Time taken: 0.000576 seconds

return require(game:GetService("ReplicatedStorage").Std.TableUtils).requireValidIndexAndFreeze({
    POOL_OBJ_PTR_NAME = "NetObjPoolItemPoolObjPtr";
    ACTIVE_OBJ_NAME = "NetObjActive";
})