local ReplicatedStorage_upvr = game:GetService("ReplicatedStorage")
local Roact_upvr = require(ReplicatedStorage_upvr.Roact)
local ClanConsts_upvr = require(ReplicatedStorage_upvr.Clan.ClanConsts)
local RoactRodux_upvr = require(ReplicatedStorage_upvr.RoactRodux)
return function(arg1) -- Line 6
    local any_extend_result1 = Roact_upvr.Component:extend("App")
    function any_extend_result1.init(arg1_2) -- Line 11
        arg1_2.aspectRatio = 1.5
        arg1_2.leaderboardInfo = {{
            ownerUserId = 2837719;
            clanName = "Good Gang";
            clanRating = tostring(2200);
            ownerName = "Xikk";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 2025110;
            clanName = "Faze";
            clanRating = tostring(2100);
            ownerName = "Badcc";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 1;
            clanName = "Baboyz";
            clanRating = tostring(1600);
            ownerName = "CritStyx";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 2;
            clanName = "CeilingFanCrew";
            clanRating = tostring(1500);
            ownerName = "CritStyx";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 2837719;
            clanName = "Nice";
            clanRating = tostring(2200);
            ownerName = "Asimo";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 2025110;
            clanName = "Faze";
            clanRating = tostring(2100);
            ownerName = "Badcc";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 1;
            clanName = "Baboyz";
            clanRating = tostring(1600);
            ownerName = "CritStyx";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 2;
            clanName = "CeilingFanCrew";
            clanRating = tostring(1500);
            ownerName = "CritStyx";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 2837719;
            clanName = "Nice";
            clanRating = tostring(2200);
            ownerName = "Asimo";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 2025110;
            clanName = "Faze";
            clanRating = tostring(2100);
            ownerName = "Badcc";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 1;
            clanName = "Baboyz";
            clanRating = tostring(1600);
            ownerName = "CritStyx";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 2;
            clanName = "CeilingFanCrew";
            clanRating = tostring(1500);
            ownerName = "CritStyx";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 2837719;
            clanName = "Nice";
            clanRating = tostring(2200);
            ownerName = "Asimo";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 2025110;
            clanName = "Faze";
            clanRating = tostring(2100);
            ownerName = "Badcc";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 1;
            clanName = "Baboyz";
            clanRating = tostring(1600);
            ownerName = "CritStyx";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 2;
            clanName = "CeilingFanCrew";
            clanRating = tostring(1500);
            ownerName = "CritStyx";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 2837719;
            clanName = "Nice";
            clanRating = tostring(2200);
            ownerName = "Asimo";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 2025110;
            clanName = "Faze";
            clanRating = tostring(2100);
            ownerName = "Badcc";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 1;
            clanName = "Baboyz";
            clanRating = tostring(1600);
            ownerName = "CritStyx";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 2;
            clanName = "CeilingFanCrew";
            clanRating = tostring(1500);
            ownerName = "CritStyx";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 2837719;
            clanName = "Nice";
            clanRating = tostring(2200);
            ownerName = "Asimo";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 2025110;
            clanName = "Faze";
            clanRating = tostring(2100);
            ownerName = "Badcc";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 1;
            clanName = "Baboyz";
            clanRating = tostring(1600);
            ownerName = "CritStyx";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 2;
            clanName = "CeilingFanCrew";
            clanRating = tostring(1500);
            ownerName = "CritStyx";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 2837719;
            clanName = "Nice";
            clanRating = tostring(2200);
            ownerName = "Asimo";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 2025110;
            clanName = "Faze";
            clanRating = tostring(2100);
            ownerName = "Badcc";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 1;
            clanName = "Baboyz";
            clanRating = tostring(1600);
            ownerName = "CritStyx";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }, {
            ownerUserId = 2;
            clanName = "CeilingFanCrew";
            clanRating = tostring(1500);
            ownerName = "CritStyx";
            clanFlagColor = ClanConsts_upvr.CLAN_COLORS[math.random(1, #ClanConsts_upvr.CLAN_COLORS)].color;
        }}
    end
    local persistentCrewStore_upvr = require(ReplicatedStorage_upvr.PersistentCrew.persistentCrewStore)
    local CrewLeaderboard_upvr = require(script.Parent.CrewLeaderboard)
    local PersistentCrewBattleConsts_upvr = require(ReplicatedStorage_upvr.PersistentCrewBattle.PersistentCrewBattleConsts)
    function any_extend_result1.render(arg1_3) -- Line 213
        return Roact_upvr.createElement(RoactRodux_upvr.StoreProvider, {
            store = persistentCrewStore_upvr;
        }, {Roact_upvr.createElement("Frame", {
            Size = UDim2.fromScale(1, 1);
        }, {
            x = Roact_upvr.createElement(CrewLeaderboard_upvr, {
                leaderboardInfo = arg1_3.leaderboardInfo;
                aspectRatio = arg1_3.aspectRatio;
                displayType = PersistentCrewBattleConsts_upvr.LEADERBOARD_DISPLAY_TYPE_ENUM.CrewsInServer;
                attemptViewClanId = function() -- Line 224, Named "attemptViewClanId"
                    print("attempting join")
                end;
            });
            Aspect = Roact_upvr.createElement("UIAspectRatioConstraint", {
                AspectRatio = arg1_3.aspectRatio;
            });
        })})
    end
    local any_mount_result1_upvr = Roact_upvr.mount(Roact_upvr.createElement(any_extend_result1), arg1)
    return function() -- Line 236
        Roact_upvr.unmount(any_mount_result1_upvr)
    end
end