return {
    Fuel = {
        Standard = {
            MaxFuel = 15;
            MeterColor = Color3.fromRGB(252, 79, 23);
            ParticleColor = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.new(0.987289, 0.311604, 0.091356)), ColorSequenceKeypoint.new(0.561667, Color3.new(0.977401, 0.286473, 0.295048)), ColorSequenceKeypoint.new(1, Color3.new(0.97023, 0.807172, 0.438758))});
            LeanAngle = -0.37699111843077515;
        };
        Rocket = {
            MaxFuel = 40;
            MeterColor = Color3.fromRGB(178, 28, 252);
            ParticleColor = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.new(0.117464, 0.606439, 0.998566)), ColorSequenceKeypoint.new(0.561667, Color3.new(0.461219, 0.206043, 0.987137)), ColorSequenceKeypoint.new(1, Color3.new(0.97023, 0.807172, 0.438758))});
            LeanAngle = -0.5654866776461628;
            ProductId = 144034773;
        };
    };
}