-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMNBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlCFNldHRpbmdzCFJlc291cmNlCEVudW1UZWFtBlBvbGljZQZ0ZWFtSWQpRWF0IGEgZG9udXQgbmV4dCB0byBhIENyaW1pbmFsLCAxMCB0aW1lcy4HbWVzc2FnZQRnb2FsCXJld2FyZEV4cAABBAAAAQIAIKMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0DAGIHAAAATQIDygYAAACfAQIC/wIDAAAAAABNAwFMCAAAAE0DA7IJAAAAMAMCbwoAAABvAwsAMAMCmAwAAACMAwoAMAMCCg0AAACMAxkAMAMCAw4AAACCAgIADwMBBAAAAEADAgMDAwQEAABAQAMFAwYDBwMIAwkDCgMLAwwDDQABAAEYAAAAAAAAAAEAAAAAAAACAAEAAAAAAAEAAAEAAAEAAAEBAAAAAAC91WZlJVs3nWTUVVQvvDEEzc1xEY8RDGQ=

-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2026-04-18 23:35:30
-- Luau version 6, Types version 3
-- Time taken: 0.000586 seconds

return {
    teamId = require(game:GetService("ReplicatedStorage").Resource.Settings).EnumTeam.Police;
    message = "Eat a donut next to a Criminal, 10 times.";
    goal = 10;
    rewardExp = 25;
}