-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMMBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplFU1JU1NJTEVfT0JKX1BPT0xfTkFNRQ9ST0NLRVRfVEFHX05BTUUZU0VFS0lOR19MT0NLX01JTl9EVVJBVElPTh9Sb2NrZXRMYXVuY2hlckhvbGRlck1pc3NpbGVQb29sFFJvY2tldExhdW5jaGVyUm9ja2V0AAEFAAABAgAcowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQIAoQYAAABNAgIYBwAAAJ8BAgJNAgEACAAAAOIDDABvBA0AMAQDeAkAAABvBA4AMAQDpAoAAACMBAIAMAQDjgsAAACfAgIAggIAAA8DAQQAAABAAwIDAwMEBAAAQEADBQMGAwcDCAMJAwoFAwkKCwMLAwwAAQABGAAAAAAAAAABAAAAAAAAAQAAAQAAAQAAAQAA/QABAAAAAADcaoBYo+4Bo6bsExpcz7/drHKXLO6u6lk=

-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2026-04-18 23:45:34
-- Luau version 6, Types version 3
-- Time taken: 0.000456 seconds

return require(game:GetService("ReplicatedStorage").Std.TableUtils).requireValidIndexAndFreeze({
    MISSILE_OBJ_POOL_NAME = "RocketLauncherHolderMissilePool";
    ROCKET_TAG_NAME = "RocketLauncherRocket";
    SEEKING_LOCK_MIN_DURATION = 2;
})