-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMHBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlDlJvY2tldExhdW5jaGVyGlJvY2tldExhdW5jaGVyUm9ja2V0QmluZGVyBVN0YXJ0AAEEAAABAgASowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQIA0wYAAABNAgJRBwAAAJ8BAgK8AgEcCAAAAJ8CAgGCAAEACQMBBAAAAEADAgMDAwQEAABAQAMFAwYDBwABAAEYAAAAAAAAAAEAAAAAAAABAAABAQAAAAAA

-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2026-04-18 23:29:50
-- Luau version 6, Types version 3
-- Time taken: 0.000441 seconds

require(game:GetService("ReplicatedStorage").RocketLauncher.RocketLauncherRocketBinder):Start()