-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMFB3JlcXVpcmUGc2NyaXB0DVN0b3JlUHJvdmlkZXIHY29ubmVjdBFVTlNUQUJMRV9jb25uZWN0MgABAwAAAQIAF6MAAACkAAEAAAAAQKQBAwAAACBATQEBugQAAACfAAICpAEBAAAAAECkAgMAAAAgQE0CAucFAAAAnwECAuICBwAwAAK6BAAAADABAucFAAAAMAECBAYAAACCAgIACAMBBAAAAEADAgQAACBAAwMDBAMFBQMEBQYAAQABGAAAAAAAAAAAAQAAAAAAAAIBAAEAAQAAAQAAAAAA

-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2026-04-18 23:31:35
-- Luau version 6, Types version 3
-- Time taken: 0.000412 seconds

local connect = require(script.connect)
return {
    StoreProvider = require(script.StoreProvider);
    connect = connect;
    UNSTABLE_connect2 = connect;
}