-- Reviewed by Claude
return {
	["Vehicle.JackRabbit"] = {
		CreatorName = "oof_ed",
		CreatorUserId = 551992971
	},
	["Vehicle.Celsior"] = {
		CreatorName = "Sharky_Cat109",
		CreatorUserId = 146212681
	},
	["Vehicle.Badger"] = {
		CreatorName = "RallySubbie",
		CreatorUserId = 71744786
	},
	["Vehicle.IceBreaker"] = {
		CreatorName = "Italimpexfx",
		CreatorUserId = 173543636
	},
	["Vehicle.Tank"] = {
		CreatorName = "RallySubbie",
		CreatorUserId = 71744786
	},
	["Vehicle.Beignet"] = {
		CreatorName = "RallySubbie",
		CreatorUserId = 71744786
	},
	["Vehicle.Trailblazer"] = {
		CreatorName = "Sharky_Cat109",
		CreatorUserId = 146212681
	},
	["Vehicle.Ray9"] = {
		CreatorName = "ItzTruminator",
		CreatorUserId = 996508101
	},
	["Vehicle.TheCamper"] = {
		CreatorName = "Ickleon37",
		CreatorUserId = 847255377
	},
	["Vehicle.BananaCar"] = {
		CreatorName = "ZuperPro1",
		CreatorUserId = 1392743315
	},
	["Vehicle.Sentinel"] = {
		CreatorName = "Ickleon37",
		CreatorUserId = 847255377
	},
	["Vehicle.TheRattler"] = {
		CreatorName = "ShadowSamurai720",
		CreatorUserId = 391034465
	},
	["Vehicle.TheAgent"] = {
		CreatorName = "Zewo_Tsu",
		CreatorUserId = 102700598
	},
	["Vehicle.MoltenM12"] = {
		CreatorName = "RallySubbie",
		CreatorUserId = 71744786
	},
	["Vehicle.Chiron"] = {
		CreatorName = "Pizzawroles",
		CreatorUserId = 1469260571
	},
	["Vehicle.Stunt"] = {
		CreatorName = "Zewo_Tsu",
		CreatorUserId = 102700598
	},
	["Vehicle.BlackHawk"] = {
		CreatorName = "oof_ed",
		CreatorUserId = 551992971
	},
	["Vehicle.Volt"] = {
		CreatorName = "TommyIsDaBoss",
		CreatorUserId = 405577649
	},
	["VehicleCustomization.Rim.IronRock"] = {
		CreatorName = "DydyWasTaken",
		CreatorUserId = 591295581
	},
	["VehicleCustomization.Rim.Beadlock"] = {
		CreatorName = "Zewo_Tsu",
		CreatorUserId = 102700598
	},
	["VehicleCustomization.Rim.Energized"] = {
		CreatorName = "SpeedQue3n",
		CreatorUserId = 2463010296
	},
	["VehicleCustomization.Rim.Ionize"] = {
		CreatorName = "TOPrime1",
		CreatorUserId = 1367814618
	},
	["VehicleCustomization.Rim.Trion"] = {
		CreatorName = "ItzTruminator",
		CreatorUserId = 996508101
	},
	["VehicleCustomization.Rim.SnowFace"] = {
		CreatorName = "Sy_hm",
		CreatorUserId = 119028551
	},
	["VehicleCustomization.Rim.Icicle"] = {
		CreatorName = "ZuperPro1",
		CreatorUserId = 1392743315
	},
	["VehicleCustomization.Rim.RetroRacer"] = {
		CreatorName = "Zewo_Tsu",
		CreatorUserId = 102700598
	},
	["VehicleCustomization.Rim.CenterLock"] = {
		CreatorName = "ItzTruminator",
		CreatorUserId = 996508101
	},
	["VehicleCustomization.Rim.RTX"] = {
		CreatorName = "Animatemeteor",
		CreatorUserId = 1183249568
	},
	["VehicleCustomization.Rim.Compass"] = {
		CreatorName = "ZuperPro1",
		CreatorUserId = 1392743315
	},
	["VehicleCustomization.Rim.Bonded"] = {
		CreatorName = "Zewo_Tsu",
		CreatorUserId = 102700598
	},
	["VehicleCustomization.Rim.Bull"] = {
		CreatorName = "RallySubbie",
		CreatorUserId = 71744786
	},
	["VehicleCustomization.Spoiler.TravelCase"] = {
		CreatorName = "ObviouslyPurple",
		CreatorUserId = 341680229
	},
	["VehicleCustomization.Spoiler.Glider"] = {
		CreatorName = "SpeedQue3n",
		CreatorUserId = 2463010296
	},
	["VehicleCustomization.Spoiler.BicycleRack"] = {
		CreatorName = "Ickleon37",
		CreatorUserId = 847255377
	},
	["VehicleCustomization.Spoiler.MechaArm"] = {
		CreatorName = "Fakergenc",
		CreatorUserId = 399158320
	},
	["VehicleCustomization.Spoiler.Overdrive"] = {
		CreatorName = "happyhongo",
		CreatorUserId = 280742494
	},
	["VehicleCustomization.Spoiler.SnowShovel"] = {
		CreatorName = "Ickleon37",
		CreatorUserId = 847255377
	},
	["VehicleCustomization.Spoiler.SnowLog"] = {
		CreatorName = "SpeedQue3n",
		CreatorUserId = 2463010296
	},
	["VehicleCustomization.Spoiler.Velocity"] = {
		CreatorName = "MazeGFX",
		CreatorUserId = 125083697
	},
	["VehicleCustomization.Spoiler.JDM"] = {
		CreatorName = "Sy_hm",
		CreatorUserId = 119028551
	},
	["VehicleCustomization.Spoiler.Clickbait"] = {
		CreatorName = "GladyAshley",
		CreatorUserId = 62046764
	},
	["VehicleCustomization.Spoiler.Tuner"] = {
		CreatorName = "Sharky_Cat109",
		CreatorUserId = 146212681
	},
	["VehicleCustomization.Spoiler.Eternal Flame"] = {
		CreatorName = "GR86Jailbreak",
		CreatorUserId = 290401205
	},
	["VehicleCustomization.Spoiler.Tiki Torch"] = {
		CreatorName = "INOUGAAT",
		CreatorUserId = 1583961866
	},
	["VehicleCustomization.Spoiler.Deathtrap"] = {
		CreatorName = "Coynese",
		CreatorUserId = 122022022
	},
	["HomeItem.Air Hockey Table"] = {
		CreatorName = "101InspiringLimestone",
		CreatorUserId = 1105847504
	},
	["HomeItem.Car Pool Table"] = {
		CreatorName = "101InspiringLimestone",
		CreatorUserId = 1105847504
	},
	["HomeItem.Gamer Chair"] = {
		CreatorName = "happyhongo",
		CreatorUserId = 280742494
	},
	["HomeItem.Hot Chocolate Tub"] = {
		CreatorName = "Fakergenc",
		CreatorUserId = 399158320
	},
	["HomeItem.IfIHadOne"] = {
		CreatorName = "RallySubbie",
		CreatorUserId = 71744786
	},
	["HomeItem.Noob Scream"] = {
		CreatorName = "SpiderX750",
		CreatorUserId = 516474520
	},
	["HomeItem.Picnic Table"] = {
		CreatorName = "EyesOfObl1vion",
		CreatorUserId = 291914572
	},
	["HomeItem.Race Simulator"] = {
		CreatorName = "Zewo_Tsu",
		CreatorUserId = 102700598
	},
	["HomeItem.Racecar Bed"] = {
		CreatorName = "oof_ed",
		CreatorUserId = 551992971
	},
	["HomeItem.Sarcophagus Bed"] = {
		CreatorName = "WalliBalli",
		CreatorUserId = 72885471
	},
	["HomeItem.Sci-Fi Kitchen"] = {
		CreatorName = "Ihtlove",
		CreatorUserId = 397989560
	},
	["HomeItem.Teleporters"] = {
		CreatorName = "101InspiringLimestone",
		CreatorUserId = 1105847504
	},
	["HomeItem.Tiger Rug"] = {
		CreatorName = "lechugo_",
		CreatorUserId = 130450376
	},
	["HomeItem.Trapped Bookshelf"] = {
		CreatorName = "Coynese",
		CreatorUserId = 122022022
	},
	["VehicleCustomization.Texture.DirtRally"] = {
		CreatorName = "ShadowSamurai720",
		CreatorUserId = 391034465
	},
	["VehicleCustomization.Texture.NASCAR1"] = {
		CreatorName = "door979hungry",
		CreatorUserId = 969529629
	},
	["VehicleCustomization.Texture.NASCAR2"] = {
		CreatorName = "Hurricane_48",
		CreatorUserId = 114966173
	},
	["VehicleCustomization.Texture.CircuitBoard"] = {
		CreatorName = "ItzTruminator",
		CreatorUserId = 996508101
	},
	["VehicleCustomization.Texture.IceCamo"] = {
		CreatorName = "Fakergenc",
		CreatorUserId = 399158320
	},
	["VehicleCustomization.Texture.BlackIce"] = {
		CreatorName = "ShadowSamurai720",
		CreatorUserId = 391034465
	},
	["VehicleCustomization.Texture.Gulf"] = {
		CreatorName = "Fakergenc",
		CreatorUserId = 399158320
	},
	["VehicleCustomization.Texture.Flaming"] = {
		CreatorName = "ItzTruminator",
		CreatorUserId = 996508101
	},
	["VehicleCustomization.Texture.Drip"] = {
		CreatorName = "Fakergenc",
		CreatorUserId = 399158320
	},
	["VehicleCustomization.Texture.CrimsonRacer"] = {
		CreatorName = "Fakergenc",
		CreatorUserId = 399158320
	},
	["VehicleCustomization.Texture.Earthquake"] = {
		CreatorName = "Coynese",
		CreatorUserId = 122022022
	},
	["VehicleCustomization.Texture.Galaxy"] = {
		CreatorName = "Ickleon37",
		CreatorUserId = 847255377
	},
	["VehicleCustomization.Spoiler.TrophyWings"] = {
		CreatorName = "EyesOfObl1vion",
		CreatorUserId = 291914572
	},
	["HomeItem.Walk Of Fame"] = {
		CreatorName = "wiphiax",
		CreatorUserId = 2502397118
	},
	["VehicleCustomization.Rim.Roll-X"] = {
		CreatorName = "SpeedQue3n",
		CreatorUserId = 2463010296
	},
	["HomeItem.Royal Throne"] = {
		CreatorName = "EyesOfObl1vion",
		CreatorUserId = 291914572
	},
	["VehicleCustomization.Spoiler.CashSpitter"] = {
		CreatorName = "ShadowSamurai720",
		CreatorUserId = 391034465
	},
	["VehicleCustomization.Texture.WhiteMarble"] = {
		CreatorName = "Ickleon37",
		CreatorUserId = 847255377
	},
	["VehicleCustomization.Rim.DiamondEngrave"] = {
		CreatorName = "oof_ed",
		CreatorUserId = 551992971
	},
	["Vehicle.Macaron"] = {
		CreatorName = "DydyWasTaken",
		CreatorUserId = 591295581
	},
	["VehicleCustomization.Texture.Superstar"] = {
		CreatorName = "ShadowSamurai720",
		CreatorUserId = 391034465
	},
	["ItemSkin.WhiteMarble"] = {
		CreatorName = "Ickleon37",
		CreatorUserId = 847255377
	},
	["ItemSkin.CircuitBoard"] = {
		CreatorName = "ItzTruminator",
		CreatorUserId = 996508101
	},
	["ItemSkin.BlackIce"] = {
		CreatorName = "ShadowSamurai720",
		CreatorUserId = 391034465
	},
	["ItemSkin.Flaming"] = {
		CreatorName = "ItzTruminator",
		CreatorUserId = 996508101
	},
	["ItemSkin.Drip"] = {
		CreatorName = "Fakergenc",
		CreatorUserId = 399158320
	},
	["ItemSkin.Earthquake"] = {
		CreatorName = "Coynese",
		CreatorUserId = 122022022
	},
	["Vehicle.Snake"] = {
		CreatorName = "oof_ed",
		CreatorUserId = 551992971
	},
	["Vehicle.ShellClassic"] = {
		CreatorName = "oof_ed",
		CreatorUserId = 551992971
	},
	["VehicleCustomization.Texture.RoadWarrior"] = {
		CreatorName = "Memecellent",
		CreatorUserId = 304033025
	},
	["VehicleCustomization.Rim.Tesseract"] = {
		CreatorName = "ShadowSamurai720",
		CreatorUserId = 391034465
	},
	["VehicleCustomization.Rim.HoldE"] = {
		CreatorName = "SpeedQue3n",
		CreatorUserId = 2463010296
	},
	["VehicleCustomization.Rim.Doubloon"] = {
		CreatorName = "happyhongo",
		CreatorUserId = 280742494
	},
	["VehicleCustomization.Rim.Rally"] = {
		CreatorName = "Plasmazillah",
		CreatorUserId = 1009227115
	},
	["VehicleCustomization.Rim.PoliceChase"] = {
		CreatorName = "ItzTruminator",
		CreatorUserId = 996508101
	},
	["VehicleCustomization.Rim.RFX"] = {
		CreatorName = "ItzTruminator",
		CreatorUserId = 996508101
	},
	["VehicleCustomization.Rim.Abstracts"] = {
		CreatorName = "oof_ed",
		CreatorUserId = 551992971
	},
	["VehicleCustomization.Rim.Slashers"] = {
		CreatorName = "SpeedQue3n",
		CreatorUserId = 2463010296
	},
	["VehicleCustomization.Rim.VaultDoor"] = {
		CreatorName = "Mrzimerman",
		CreatorUserId = 467556170
	},
	["VehicleCustomization.TireSticker.Badonuts"] = {
		CreatorName = "ItzTruminator",
		CreatorUserId = 996508101
	},
	["VehicleCustomization.TireSticker.Construction"] = {
		CreatorName = "Memecellent",
		CreatorUserId = 304033025
	},
	["VehicleCustomization.TireSticker.Tracer"] = {
		CreatorName = "TotallyTyler",
		CreatorUserId = 307429300
	},
	["VehicleCustomization.TireSticker.Japanese"] = {
		CreatorName = "Memecellent",
		CreatorUserId = 304033025
	},
	["VehicleCustomization.TireSticker.Speed"] = {
		CreatorName = "GoldenTempezt1",
		CreatorUserId = 519222556
	},
	["VehicleCustomization.TireSticker.Lightning"] = {
		CreatorName = "ShadowSamurai720",
		CreatorUserId = 391034465
	},
	["VehicleCustomization.Spoiler.Terminator"] = {
		CreatorName = "Poogah",
		CreatorUserId = 2267756092
	},
	["VehicleCustomization.Spoiler.FlameSpitter"] = {
		CreatorName = "ShadowSamurai720",
		CreatorUserId = 391034465
	},
	["VehicleCustomization.Spoiler.AerialSupport"] = {
		CreatorName = "Sy_hm",
		CreatorUserId = 119028551
	},
	["VehicleCustomization.Spoiler.GTR"] = {
		CreatorName = "oof_ed",
		CreatorUserId = 551992971
	},
	["VehicleCustomization.Spoiler.Racer"] = {
		CreatorName = "TSHenry139",
		CreatorUserId = 386633921
	},
	["VehicleCustomization.Spoiler.DragonBreath"] = {
		CreatorName = "EyesOfObl1vion",
		CreatorUserId = 291914572
	},
	["VehicleCustomization.Spoiler.King"] = {
		CreatorName = "wiphiax",
		CreatorUserId = 2502397118
	},
	["HomeItem.Toy Plane"] = {
		CreatorName = "ANOUHM",
		CreatorUserId = 42486718
	},
	["HomeItem.CyberBlue Couch"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["HomeItem.Grand Piano"] = {
		CreatorName = "Dr_Radium",
		CreatorUserId = 1308015890
	},
	["HomeItem.Dino Exhibit"] = {
		CreatorName = "Sardaji154",
		CreatorUserId = 1420413811
	},
	["VehicleCustomization.Rim.TeddyBear"] = {
		CreatorName = "EyesOfObl1vion",
		CreatorUserId = 291914572
	},
	["HomeItem.PuzzleCouch"] = {
		CreatorName = "Dr_Radium",
		CreatorUserId = 1308015890
	},
	["VehicleCustomization.Spoiler.RemoteControl"] = {
		CreatorName = "MrSSR_55",
		CreatorUserId = 376540757
	},
	["VehicleCustomization.Rim.TrackToy"] = {
		CreatorName = "Dr_Radium",
		CreatorUserId = 1308015890
	},
	["VehicleCustomization.Texture.WoodenToy"] = {
		CreatorName = "Ickleon37",
		CreatorUserId = 847255377
	},
	["VehicleCustomization.Spoiler.WaterGun"] = {
		CreatorName = "SpeedQue3n",
		CreatorUserId = 2463010296
	},
	["VehicleCustomization.Spoiler.Jetpack"] = {
		CreatorName = "SpeedQue3n",
		CreatorUserId = 2463010296
	},
	["Vehicle.Bloxy"] = {
		CreatorName = "Sharky_Cat109",
		CreatorUserId = 146212681
	},
	["VehicleCustomization.Spoiler.TurningKey"] = {
		CreatorName = "happyhongo",
		CreatorUserId = 280742494
	},
	["VehicleCustomization.TireSticker.DatBrian"] = {
		CreatorName = "Shadowg53632543",
		CreatorUserId = 795962402
	},
	["VehicleCustomization.TireSticker.Phindr"] = {
		CreatorName = "coolgamr1638",
		CreatorUserId = 461691848
	},
	["VehicleCustomization.Rim.Revolver"] = {
		CreatorName = "Uthreon",
		CreatorUserId = 2412225352
	},
	["VehicleCustomization.Rim.Forged"] = {
		CreatorName = "Uthreon",
		CreatorUserId = 2412225352
	},
	["VehicleCustomization.Spoiler.Spares"] = {
		CreatorName = "deNolD14",
		CreatorUserId = 304925488
	},
	["VehicleCustomization.Rim.Reactor"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["VehicleCustomization.Rim.Propeller"] = {
		CreatorName = "Plasmazillah",
		CreatorUserId = 1009227115
	},
	["HomeItem.CosmeticSafe"] = {
		CreatorName = "Dr_Radium",
		CreatorUserId = 1308015890
	},
	["VehicleCustomization.Rim.DragonChaser"] = {
		CreatorName = "wiphiax",
		CreatorUserId = 2502397118
	},
	["VehicleCustomization.Rim.Radioactive"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["VehicleCustomization.Texture.CarbonFire"] = {
		CreatorName = "Fakergenc",
		CreatorUserId = 399158320
	},
	["VehicleCustomization.Spoiler.Tank Wing"] = {
		CreatorName = "Sharky_Cat109",
		CreatorUserId = 146212681
	},
	["VehicleCustomization.TireSticker.JailbreakArmy"] = {
		CreatorName = "Memecellent",
		CreatorUserId = 304033025
	},
	["HomeItem.MissileBed"] = {
		CreatorName = "MrOofxD",
		CreatorUserId = 367225191
	},
	["VehicleCustomization.Rim.Scope"] = {
		CreatorName = "SpeedQue3n",
		CreatorUserId = 2463010296
	},
	["HomeItem.NukamoFridge"] = {
		CreatorName = "MrSSR_55",
		CreatorUserId = 376540757
	},
	["VehicleCustomization.Spoiler.Afterburner"] = {
		CreatorName = "Sharky_Cat109",
		CreatorUserId = 146212681
	},
	["VehicleCustomization.Texture.CamoRadar"] = {
		CreatorName = "Fakergenc",
		CreatorUserId = 399158320
	},
	["Vehicle.Goliath"] = {
		CreatorName = "ShadowSamurai720",
		CreatorUserId = 391034465
	},
	["Vehicle.ShellMark5"] = {
		CreatorName = "AMiguent",
		CreatorUserId = 469555177
	},
	["VehicleCustomization.Spoiler.Mark5"] = {
		CreatorName = "AMiguent",
		CreatorUserId = 469555177
	},
	["Vehicle.DesertCrawler"] = {
		CreatorName = "SpeedQue3n",
		CreatorUserId = 2463010296
	},
	["Vehicle.Javelin"] = {
		CreatorName = "oof_ed",
		CreatorUserId = 551992971
	},
	["VehicleCustomization.Spoiler.Deathray"] = {
		CreatorName = "ShadowSamurai720",
		CreatorUserId = 391034465
	},
	["HomeItem.Hero Zapper"] = {
		CreatorName = "Memecellent",
		CreatorUserId = 304033025
	},
	["VehicleCustomization.Spoiler.Flamethrower"] = {
		CreatorName = "Guest5152536177",
		CreatorUserId = 975558520
	},
	["VehicleCustomization.Rim.UnknownSignal"] = {
		CreatorName = "NotPolarization",
		CreatorUserId = 125924505
	},
	["HomeItem.Cryo Chamber"] = {
		CreatorName = "Sharky_Cat109",
		CreatorUserId = 146212681
	},
	["VehicleCustomization.Texture.Lava"] = {
		CreatorName = "Memecellent",
		CreatorUserId = 304033025
	},
	["VehicleCustomization.Rim.LaserCannon"] = {
		CreatorName = "Sharky_Cat109",
		CreatorUserId = 146212681
	},
	["Vehicle.Bandit"] = {
		CreatorName = "Howsel",
		CreatorUserId = 93146994
	},
	["VehicleCustomization.Rim.Sawblade"] = {
		CreatorName = "Plasmazillah",
		CreatorUserId = 1009227115
	},
	["VehicleCustomization.Spoiler.Harpoon"] = {
		CreatorName = "deNolD14",
		CreatorUserId = 304925488
	},
	["VehicleCustomization.Rim.Electrostatic"] = {
		CreatorName = "ShadowSamurai720",
		CreatorUserId = 391034465
	},
	["HomeItem.TNT Barrel"] = {
		CreatorName = "Plasmazillah",
		CreatorUserId = 1009227115
	},
	["Vehicle.EscapeBot"] = {
		CreatorName = "happyhongo",
		CreatorUserId = 280742494
	},
	["Vehicle.Crown"] = {
		CreatorName = "happyhongo",
		CreatorUserId = 280742494
	},
	["VehicleCustomization.TireSticker.Champion"] = {
		CreatorName = "Shadowg53632543",
		CreatorUserId = 795962402
	},
	["VehicleCustomization.Rim.Baller"] = {
		CreatorName = "Plasmazillah",
		CreatorUserId = 1009227115
	},
	["VehicleCustomization.Texture.Touchdown"] = {
		CreatorName = "Poogah",
		CreatorUserId = 2267756092
	},
	["HomeItem.Foosball Table"] = {
		CreatorName = "Memecellent",
		CreatorUserId = 304033025
	},
	["VehicleCustomization.Spoiler.DoYouLift"] = {
		CreatorName = "SpeedQue3n",
		CreatorUserId = 2463010296
	},
	["VehicleCustomization.Rim.Fore"] = {
		CreatorName = "Spooxyz_1337",
		CreatorUserId = 282830065
	},
	["HomeItem.Arcade Sports Machine"] = {
		CreatorName = "ZushiiiSushiii",
		CreatorUserId = 441750924
	},
	["VehicleCustomization.Spoiler.EnduranceWing"] = {
		CreatorName = "Guest5152536177",
		CreatorUserId = 975558520
	},
	["Vehicle.Proto8"] = {
		CreatorName = "SpeedQue3n",
		CreatorUserId = 2463010296
	},
	["Vehicle.Parisian"] = {
		CreatorName = "Zewo_Tsu",
		CreatorUserId = 102700598
	},
	["VehicleCustomization.Rim.EXP1"] = {
		CreatorName = "Zewo_Tsu",
		CreatorUserId = 102700598
	},
	["Vehicle.Semi"] = {
		CreatorName = "Ickleon37",
		CreatorUserId = 847255377
	},
	["VehicleCustomization.TireSticker.Tokyo"] = {
		CreatorName = "Yasaph",
		CreatorUserId = 1078791470
	},
	["HomeItem.Sakura Tree"] = {
		CreatorName = "deNolD14",
		CreatorUserId = 304925488
	},
	["VehicleCustomization.Spoiler.ToriiGate"] = {
		CreatorName = "THEDOMINATOR122",
		CreatorUserId = 1828635750
	},
	["VehicleCustomization.Spoiler.JapaneseLantern"] = {
		CreatorName = "deNolD14",
		CreatorUserId = 304925488
	},
	["HomeItem.Japanese Neon Sign"] = {
		CreatorName = "Poogah",
		CreatorUserId = 2267756092
	},
	["VehicleCustomization.Rim.Stance"] = {
		CreatorName = "Sharky_Cat109",
		CreatorUserId = 146212681
	},
	["VehicleCustomization.Texture.Manga"] = {
		CreatorName = "Ickleon37",
		CreatorUserId = 847255377
	},
	["VehicleCustomization.Rim.Sakura"] = {
		CreatorName = "deNolD14",
		CreatorUserId = 304925488
	},
	["Vehicle.Shogun"] = {
		CreatorName = "EyesOfObl1vion",
		CreatorUserId = 291914572
	},
	["VehicleCustomization.TireSticker.Kanagawa"] = {
		CreatorName = "GoldenTempezt1",
		CreatorUserId = 519222556
	},
	["VehicleCustomization.Spoiler.Shogun"] = {
		CreatorName = "EyesOfObl1vion",
		CreatorUserId = 291914572
	},
	["VehicleCustomization.Texture.Shogun"] = {
		CreatorName = "EyesOfObl1vion",
		CreatorUserId = 291914572
	},
	["VehicleCustomization.Texture.PatchyJeans"] = {
		CreatorName = "Ickleon37",
		CreatorUserId = 847255377
	},
	["VehicleCustomization.Texture.DesertCamo"] = {
		CreatorName = "Ickleon37",
		CreatorUserId = 847255377
	},
	["VehicleCustomization.Texture.DeepPurpleFlame"] = {
		CreatorName = "Ickleon37",
		CreatorUserId = 847255377
	},
	["VehicleCustomization.Texture.Watermelon"] = {
		CreatorName = "Ickleon37",
		CreatorUserId = 847255377
	},
	["VehicleCustomization.Texture.DragonScales"] = {
		CreatorName = "Ickleon37",
		CreatorUserId = 847255377
	},
	["VehicleCustomization.Texture.NuclearWaste"] = {
		CreatorName = "Ickleon37",
		CreatorUserId = 847255377
	},
	["HomeItem.BombChandelier"] = {
		CreatorName = "Ickleon37",
		CreatorUserId = 847255377
	},
	["HomeItem.CatPlush"] = {
		CreatorName = "Sy_hm",
		CreatorUserId = 119028551
	},
	["HomeItem.ConspiracyBoard"] = {
		CreatorName = "eggnog8483",
		CreatorUserId = 143494686
	},
	["HomeItem.DeepSeaAquarium"] = {
		CreatorName = "SpeedQue3n",
		CreatorUserId = 2463010296
	},
	["HomeItem.DJBooth"] = {
		CreatorName = "SpeedQue3n",
		CreatorUserId = 2463010296
	},
	["HomeItem.DriftwoodShelves"] = {
		CreatorName = "Yasaph",
		CreatorUserId = 1078791470
	},
	["HomeItem.Drumset"] = {
		CreatorName = "Poogah",
		CreatorUserId = 2267756092
	},
	["HomeItem.FancyWallLamp"] = {
		CreatorName = "Kunil_games",
		CreatorUserId = 1147296752
	},
	["HomeItem.FancyFireplace"] = {
		CreatorName = "Kunil_games",
		CreatorUserId = 1147296752
	},
	["HomeItem.LavaLamp"] = {
		CreatorName = "Poogah",
		CreatorUserId = 2267756092
	},
	["HomeItem.ModKitchen"] = {
		CreatorName = "MazeGFX",
		CreatorUserId = 125083697
	},
	["HomeItem.ModKitchenIsland"] = {
		CreatorName = "MazeGFX",
		CreatorUserId = 125083697
	},
	["HomeItem.ModernKingBed"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["HomeItem.NightTrainArtwork"] = {
		CreatorName = "mefijoso",
		CreatorUserId = 370761383
	},
	["HomeItem.OakArmChair"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["HomeItem.OakArmSofa"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["HomeItem.OakCoffeeTable"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["HomeItem.OrbitalChandelier"] = {
		CreatorName = "RedCrabb",
		CreatorUserId = 364269201
	},
	["HomeItem.Outlet"] = {
		CreatorName = "ShadowSamurai720",
		CreatorUserId = 391034465
	},
	["HomeItem.Pixel Portrait"] = {
		CreatorName = "deNolD14",
		CreatorUserId = 304925488
	},
	["HomeItem.RetroComputer"] = {
		CreatorName = "eggnog8483",
		CreatorUserId = 143494686
	},
	["HomeItem.SmokeDetector"] = {
		CreatorName = "ShadowSamurai720",
		CreatorUserId = 391034465
	},
	["HomeItem.SupersuitDisplay"] = {
		CreatorName = "eggnog8483",
		CreatorUserId = 143494686
	},
	["HomeItem.Switch1"] = {
		CreatorName = "ShadowSamurai720",
		CreatorUserId = 391034465
	},
	["HomeItem.Switch2"] = {
		CreatorName = "ShadowSamurai720",
		CreatorUserId = 391034465
	},
	["HomeItem.TwinSofa"] = {
		CreatorName = "Dr_Radium",
		CreatorUserId = 1308015890
	},
	["HomeItem.Vent"] = {
		CreatorName = "ShadowSamurai720",
		CreatorUserId = 391034465
	},
	["VehicleCustomization.TireSticker.Buoy"] = {
		CreatorName = "SpeedQue3n",
		CreatorUserId = 2463010296
	},
	["VehicleCustomization.Spoiler.SurfboardRack"] = {
		CreatorName = "Poogah",
		CreatorUserId = 2267756092
	},
	["VehicleCustomization.Rim.Volleyball"] = {
		CreatorName = "Poogah",
		CreatorUserId = 2267756092
	},
	["HomeItem.BeachHammock"] = {
		CreatorName = "DiamondKing",
		CreatorUserId = 83702035
	},
	["VehicleCustomization.Texture.Aquatic"] = {
		CreatorName = "Memecellent",
		CreatorUserId = 304033025
	},
	["VehicleCustomization.Rim.RubberDucky"] = {
		CreatorName = "Yasaph",
		CreatorUserId = 1078791470
	},
	["HomeItem.Tiki Tea Bar"] = {
		CreatorName = "deNolD14",
		CreatorUserId = 304925488
	},
	["VehicleCustomization.Spoiler.ShellSpeaker"] = {
		CreatorName = "deNolD14",
		CreatorUserId = 304925488
	},
	["Vehicle.Poseidon"] = {
		CreatorName = "ShadowSamurai720",
		CreatorUserId = 391034465
	},
	["VehicleCustomization.Rim.Beachball"] = {
		CreatorName = "Hriday2007",
		CreatorUserId = 852866727
	},
	["VehicleCustomization.Spoiler.Tsutek"] = {
		CreatorName = "Zewo_Tsu",
		CreatorUserId = 102700598
	},
	["VehicleCustomization.Spoiler.Dragster"] = {
		CreatorName = "Zewo_Tsu",
		CreatorUserId = 102700598
	},
	["VehicleCustomization.Rim.Unified"] = {
		CreatorName = "Zewo_Tsu",
		CreatorUserId = 102700598
	},
	["VehicleCustomization.Rim.Vecchio"] = {
		CreatorName = "Zewo_Tsu",
		CreatorUserId = 102700598
	},
	["VehicleCustomization.TireSticker.LeapYear"] = {
		CreatorName = "Zewo_Tsu",
		CreatorUserId = 102700598
	},
	["VehicleCustomization.TireSticker.Parisian"] = {
		CreatorName = "Zewo_Tsu",
		CreatorUserId = 102700598
	},
	["HomeItem.Confetti Cannon"] = {
		CreatorName = "Poogah",
		CreatorUserId = 2267756092
	},
	["VehicleCustomization.Rim.VFX"] = {
		CreatorName = "D4EAMER",
		CreatorUserId = 339428324
	},
	["VehicleCustomization.Rim.RX-1"] = {
		CreatorName = "D4EAMER",
		CreatorUserId = 339428324
	},
	["VehicleCustomization.Rim.Space-R"] = {
		CreatorName = "D4EAMER",
		CreatorUserId = 339428324
	},
	["VehicleCustomization.Spoiler.CatchMe"] = {
		CreatorName = "D4EAMER",
		CreatorUserId = 339428324
	},
	["VehicleCustomization.Spoiler.TroubleWing"] = {
		CreatorName = "D4EAMER",
		CreatorUserId = 339428324
	},
	["VehicleCustomization.TireSticker.FlagsOfEurope"] = {
		CreatorName = "SpeedQue3n",
		CreatorUserId = 2463010296
	},
	["HomeItem.LondonTelephoneSofa"] = {
		CreatorName = "deNolD14",
		CreatorUserId = 304925488
	},
	["VehicleCustomization.Rim.BelgianWaffle"] = {
		CreatorName = "Poogah",
		CreatorUserId = 2267756092
	},
	["VehicleCustomization.Rim.UKHeritage"] = {
		CreatorName = "deNolD14",
		CreatorUserId = 304925488
	},
	["HomeItem.FrenchCroissantSofa"] = {
		CreatorName = "MrOofXD",
		CreatorUserId = 367225191
	},
	["VehicleCustomization.Rim.EuroCloverleaf"] = {
		CreatorName = "NotPolarization",
		CreatorUserId = 125924505
	},
	["VehicleCustomization.Texture.BerlinGraffiti"] = {
		CreatorName = "Spooxyz_1337",
		CreatorUserId = 282830065
	},
	["VehicleCustomization.Spoiler.ColorsOfItaly"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["Vehicle.Power1"] = {
		CreatorName = "oof_ed",
		CreatorUserId = 551992971
	},
	["VehicleCustomization.Spoiler.LeaningWingOfPisa"] = {
		CreatorName = "ShadowSamurai720",
		CreatorUserId = 391034465
	},
	["Vehicle.Aperture"] = {
		CreatorName = "Stealth_Llama",
		CreatorUserId = 424239986
	},
	["VehicleCustomization.Spoiler.BoxOCash"] = {
		CreatorName = "Memecellent",
		CreatorUserId = 304033025
	},
	["VehicleCustomization.Drift.Cosmic"] = {
		CreatorName = "eggnog8483",
		CreatorUserId = 143494686
	},
	["VehicleCustomization.Texture.LeEclair"] = {
		CreatorName = "Dr_Radium",
		CreatorUserId = 1308015890
	},
	["Vehicle.Fiasco"] = {
		CreatorName = "MrOofXD",
		CreatorUserId = 367225191
	},
	["VehicleCustomization.Spoiler.Native"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["VehicleCustomization.Spoiler.Windmill"] = {
		CreatorName = "deNolD14",
		CreatorUserId = 304925488
	},
	["HomeItem.WantedBackground"] = {
		CreatorName = "deNolD14",
		CreatorUserId = 304925488
	},
	["VehicleCustomization.Spoiler.Bull"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["VehicleCustomization.Rim.Gunfire"] = {
		CreatorName = "NotPolarization",
		CreatorUserId = 125924505
	},
	["VehicleCustomization.Rim.Tumbleweed"] = {
		CreatorName = "GhostRoblox76367",
		CreatorUserId = 1128590980
	},
	["VehicleCustomization.Texture.Bandana"] = {
		CreatorName = "Poogah",
		CreatorUserId = 2267756092
	},
	["VehicleCustomization.Rim.WagonWheel"] = {
		CreatorName = "eggnog8483",
		CreatorUserId = 143494686
	},
	["Vehicle.Longhorn"] = {
		CreatorName = "EyesOfObl1vion",
		CreatorUserId = 291914572
	},
	["HomeItem.WildWestWagon"] = {
		CreatorName = "Poogah",
		CreatorUserId = 2267756092
	},
	["Vehicle.Laviolette"] = {
		CreatorName = "Zewo_Tsu",
		CreatorUserId = 102700598
	},
	["VehicleCustomization.Spoiler.NitroTank"] = {
		CreatorName = "Guest5152536177",
		CreatorUserId = 975558520
	},
	["VehicleCustomization.Rim.Mystic"] = {
		CreatorName = "GhostRoblox76367",
		CreatorUserId = 1128590980
	},
	["VehicleCustomization.Rim.Landmine"] = {
		CreatorName = "Plasmazillah",
		CreatorUserId = 1009227115
	},
	["Vehicle.Successor"] = {
		CreatorName = "ItzTruminator",
		CreatorUserId = 996508101
	},
	["Vehicle.FalconS"] = {
		CreatorName = "Guest5152536177",
		CreatorUserId = 975558520
	},
	["VehicleCustomization.Spoiler.SkiWing"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["VehicleCustomization.Rim.Marshmallow"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["HomeItem.Aurora Chandelier"] = {
		CreatorName = "ThatsLife_5",
		CreatorUserId = 3181324809
	},
	["VehicleCustomization.Spoiler.SnowCannon"] = {
		CreatorName = "deNolD14",
		CreatorUserId = 304925488
	},
	["VehicleCustomization.Rim.Peppermint"] = {
		CreatorName = "Poogah",
		CreatorUserId = 2267756092
	},
	["VehicleCustomization.TireMesh.Snowchain"] = {
		CreatorName = "eggnog8483",
		CreatorUserId = 143494686
	},
	["VehicleCustomization.Texture.Aurora"] = {
		CreatorName = "Sardaji154",
		CreatorUserId = 1420413811
	},
	["VehicleCustomization.Rim.Frostburn"] = {
		CreatorName = "NotPolarization",
		CreatorUserId = 125924505
	},
	["Vehicle.FrostCrawler"] = {
		CreatorName = "Poogah",
		CreatorUserId = 2267756092
	},
	["VehicleCustomization.Drift.Aurora"] = {
		CreatorName = "Poogah",
		CreatorUserId = 2267756092
	},
	["Vehicle.Carbonara"] = {
		CreatorName = "Plasmazillah",
		CreatorUserId = 1009227115
	},
	["VehicleCustomization.Spoiler.Carbonara"] = {
		CreatorName = "Plasmazillah",
		CreatorUserId = 1009227115
	},
	["VehicleCustomization.Spoiler.Scythes"] = {
		CreatorName = "deNolD14",
		CreatorUserId = 304925488
	},
	["VehicleCustomization.Rim.Biohazard"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["HomeItem.Radiation Radio"] = {
		CreatorName = "deNolD14",
		CreatorUserId = 304925488
	},
	["VehicleCustomization.Spoiler.Sawblade"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["VehicleCustomization.Rim.RoadWarrior"] = {
		CreatorName = "deNolD14",
		CreatorUserId = 304925488
	},
	["VehicleCustomization.Drift.Spark"] = {
		CreatorName = "Poogah",
		CreatorUserId = 2267756092
	},
	["VehicleCustomization.Texture.RoadHazard"] = {
		CreatorName = "Dr_Radium",
		CreatorUserId = 1308015890
	},
	["VehicleCustomization.TireMesh.Spiked"] = {
		CreatorName = "Poogah",
		CreatorUserId = 2267756092
	},
	["Vehicle.Striker"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["VehicleCustomization.Spoiler.Skull"] = {
		CreatorName = "NotPolarization",
		CreatorUserId = 125924505
	},
	["VehicleCustomization.Texture.Striker"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["Vehicle.XRK"] = {
		CreatorName = "D4EAMER",
		CreatorUserId = 339428324
	},
	["Vehicle.Hammerhead"] = {
		CreatorName = "MazeGFX",
		CreatorUserId = 125083697
	},
	["VehicleCustomization.Texture.CamoShark"] = {
		CreatorName = "Dr_Radium",
		CreatorUserId = 1308015890
	},
	["HomeItem.Missile Sofa"] = {
		CreatorName = "Sharky_Cat109",
		CreatorUserId = 146212681
	},
	["VehicleCustomization.Rim.SRT"] = {
		CreatorName = "NikasLis",
		CreatorUserId = 4479212217
	},
	["VehicleCustomization.Rim.Cobweb"] = {
		CreatorName = "deNolD14",
		CreatorUserId = 304925488
	},
	["VehicleCustomization.Spoiler.PoliceThatWay"] = {
		CreatorName = "ModellerCoolest",
		CreatorUserId = 102386949
	},
	["VehicleCustomization.TireSticker.Radar"] = {
		CreatorName = "Uthreon",
		CreatorUserId = 2412225352
	},
	["ItemSkin.Aquatic"] = {
		CreatorName = "Memecellent",
		CreatorUserId = 304033025
	},
	["ItemSkin.Aurora"] = {
		CreatorName = "Sardaji154",
		CreatorUserId = 1420413811
	},
	["ItemSkin.CamoRadar"] = {
		CreatorName = "Fakergenc",
		CreatorUserId = 399158320
	},
	["ItemSkin.Manga"] = {
		CreatorName = "Ickleon37",
		CreatorUserId = 847255377
	},
	["ItemSkin.WoodenToy"] = {
		CreatorName = "Ickleon37",
		CreatorUserId = 847255377
	},
	["VehicleCustomization.Spoiler.XRKAero"] = {
		CreatorName = "D4EAMER",
		CreatorUserId = 339428324
	},
	["HomeItem.Cactus Buddy"] = {
		CreatorName = "Guest5152536177",
		CreatorUserId = 975558520
	},
	["HomeItem.Fabulous Sign"] = {
		CreatorName = "DiamondKing",
		CreatorUserId = 83702035
	},
	["VehicleCustomization.Spoiler.WavingFlag"] = {
		CreatorName = "Gmantheiv",
		CreatorUserId = 129752799
	},
	["VehicleCustomization.Rim.QuarterDollar"] = {
		CreatorName = "Ocean1xs",
		CreatorUserId = 1302857292
	},
	["HomeItem.Liberty"] = {
		CreatorName = "SpeedQue3n",
		CreatorUserId = 2463010296
	},
	["VehicleCustomization.Spoiler.VintageWings"] = {
		CreatorName = "deNolD14",
		CreatorUserId = 304925488
	},
	["VehicleCustomization.TireMesh.America"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["VehicleCustomization.Texture.StarSpangled"] = {
		CreatorName = "Ickleon37",
		CreatorUserId = 847255377
	},
	["VehicleCustomization.Rim.Sparkler"] = {
		CreatorName = "Poogah",
		CreatorUserId = 2267756092
	},
	["Vehicle.Maverick"] = {
		CreatorName = "Sardaji154",
		CreatorUserId = 1420413811
	},
	["VehicleCustomization.Drift.ShootingStar"] = {
		CreatorName = "Poogah",
		CreatorUserId = 2267756092
	},
	["Vehicle.Venom"] = {
		CreatorName = "Phindr",
		CreatorUserId = 76393113
	},
	["VehicleCustomization.Rim.Roulette"] = {
		CreatorName = "Savageguy3778",
		CreatorUserId = 564850272
	},
	["VehicleCustomization.TireSticker.USA"] = {
		CreatorName = "Whizify",
		CreatorUserId = 461312609
	},
	["VehicleCustomization.TireMesh.DirtyTrail"] = {
		CreatorName = "eggnog8483",
		CreatorUserId = 143494686
	},
	["VehicleCustomization.Spoiler.Campout"] = {
		CreatorName = "eggnog8483",
		CreatorUserId = 143494686
	},
	["VehicleCustomization.Spoiler.JailbreakHills"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["VehicleCustomization.Texture.ComicConvict"] = {
		CreatorName = "Ickleon37",
		CreatorUserId = 847255377
	},
	["VehicleCustomization.TireMesh.Brickset"] = {
		CreatorName = "DydyWasTaken",
		CreatorUserId = 591295581
	},
	["Vehicle.Scorpio"] = {
		CreatorName = "Plasmazillah",
		CreatorUserId = 1009227115
	},
	["VehicleCustomization.Drift.Synth"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["VehicleCustomization.Rim.ShutterShade"] = {
		CreatorName = "GenjiTheGreater",
		CreatorUserId = 1735732063
	},
	["VehicleCustomization.Spoiler.Torero"] = {
		CreatorName = "Guest5152536177",
		CreatorUserId = 975558520
	},
	["HomeItem.80s Cassette Table"] = {
		CreatorName = "JotterB1t",
		CreatorUserId = 312481226
	},
	["VehicleCustomization.Rim.Cassette"] = {
		CreatorName = "Poogah",
		CreatorUserId = 2267756092
	},
	["VehicleCustomization.Spoiler.GuitarRiff"] = {
		CreatorName = "Thomy3DA",
		CreatorUserId = 365246708
	},
	["VehicleCustomization.Texture.Retrowave"] = {
		CreatorName = "HarmonicDust",
		CreatorUserId = 2516134171
	},
	["VehicleCustomization.Rim.Retrowave"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["Vehicle.Wedge"] = {
		CreatorName = "D4EAMER",
		CreatorUserId = 339428324
	},
	["VehicleCustomization.TireMesh.RollerBlade"] = {
		CreatorName = "Poogah",
		CreatorUserId = 2267756092
	},
	["Vehicle.Manta"] = {
		CreatorName = "Stealth_Llama",
		CreatorUserId = 424239986
	},
	["VehicleCustomization.Texture.Electronic"] = {
		CreatorName = "Poogah",
		CreatorUserId = 2267756092
	},
	["VehicleCustomization.Rim.BoominSpeaker"] = {
		CreatorName = "Thomy3DA",
		CreatorUserId = 365246708
	},
	["VehicleCustomization.TireMesh.Cheeseburger"] = {
		CreatorName = "ShadowSamurai720",
		CreatorUserId = 391034465
	},
	["VehicleCustomization.Spoiler.SkaterWing"] = {
		CreatorName = "Ocean1xs",
		CreatorUserId = 1302857292
	},
	["VehicleCustomization.Rim.EvilEye"] = {
		CreatorName = "NotPolarization",
		CreatorUserId = 125924505
	},
	["VehicleCustomization.TireSticker.80sStyle"] = {
		CreatorName = "i_m_FYRE",
		CreatorUserId = 3038531583
	},
	["VehicleCustomization.Rim.IceCrystal"] = {
		CreatorName = "GenjiTheGreater",
		CreatorUserId = 1735732063
	},
	["VehicleCustomization.Spoiler.Hazards"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["HomeItem.Winter Rally Lamp"] = {
		CreatorName = "deNolD14",
		CreatorUserId = 304925488
	},
	["VehicleCustomization.Rim.SledVoid"] = {
		CreatorName = "Thomy3DA",
		CreatorUserId = 365246708
	},
	["VehicleCustomization.Texture.AlpineRacer"] = {
		CreatorName = "Ocean1xs",
		CreatorUserId = 1302857292
	},
	["VehicleCustomization.Drift.IceSpike"] = {
		CreatorName = "Whizify",
		CreatorUserId = 461312609
	},
	["VehicleCustomization.Spoiler.RallySpotlight"] = {
		CreatorName = "deNolD14",
		CreatorUserId = 304925488
	},
	["VehicleCustomization.TireMesh.SnowTrail"] = {
		CreatorName = "Kunil_games",
		CreatorUserId = 1147296752
	},
	["Vehicle.Stormrider"] = {
		CreatorName = "Ickleon37",
		CreatorUserId = 847255377
	},
	["VehicleCustomization.TireMesh.Glacier"] = {
		CreatorName = "eggnog8483",
		CreatorUserId = 143494686
	},
	["Vehicle.Tanker"] = {
		CreatorName = "SwarmerXXXL",
		CreatorUserId = 1234289052
	},
	["Vehicle.Iceborn"] = {
		CreatorName = "DrEzekielPlays",
		CreatorUserId = 2428138161
	},
	["VehicleCustomization.Spoiler.Voxel"] = {
		CreatorName = "deNolD14",
		CreatorUserId = 304925488
	},
	["HomeItem.Arcade Portal"] = {
		CreatorName = "TheGamingSquad_",
		CreatorUserId = 934409226
	},
	["VehicleCustomization.Rim.8-Bit"] = {
		CreatorName = "SpeedQue3n",
		CreatorUserId = 2463010296
	},
	["VehicleCustomization.Spoiler.ArcadeRacer"] = {
		CreatorName = "GenjiTheGreater",
		CreatorUserId = 1735732063
	},
	["HomeItem.Pixel Campfire"] = {
		CreatorName = "Thomy3DA",
		CreatorUserId = 365246708
	},
	["VehicleCustomization.Rim.Spixel"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["VehicleCustomization.Texture.BluePixelRacer"] = {
		CreatorName = "Dr_Radium",
		CreatorUserId = 1308015890
	},
	["VehicleCustomization.Rim.Pixeltary"] = {
		CreatorName = "Thomy3DA",
		CreatorUserId = 365246708
	},
	["Vehicle.Revox"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["VehicleCustomization.Drift.PixelCoin"] = {
		CreatorName = "GenjiTheGreater",
		CreatorUserId = 1735732063
	},
	["VehicleCustomization.Spoiler.3Lives"] = {
		CreatorName = "Dr_Radium",
		CreatorUserId = 1308015890
	},
	["VehicleCustomization.Rim.GrandePunto"] = {
		CreatorName = "DaRealAlexx_",
		CreatorUserId = 1094473683
	},
	["VehicleCustomization.TireMesh.RTX"] = {
		CreatorName = "TheGamingSquad_",
		CreatorUserId = 934409226
	},
	["VehicleCustomization.TireSticker.InsertCoin"] = {
		CreatorName = "i_m_FYRE ",
		CreatorUserId = 3038531583
	},
	["VehicleCustomization.TireSticker.HungrySnake"] = {
		CreatorName = "Ne1lyh",
		CreatorUserId = 2239168270
	},
	["HomeItem.8-Bit Rug"] = {
		CreatorName = "SpeedQue3n",
		CreatorUserId = 2463010296
	},
	["HomeItem.Badimo Bros Wall Light"] = {
		CreatorName = "Dr_Radium",
		CreatorUserId = 1308015890
	},
	["HomeItem.Gamer TV Set"] = {
		CreatorName = "i_m_FYRE ",
		CreatorUserId = 3038531583
	},
	["HomeItem.Voxel Sofa"] = {
		CreatorName = "Ne1lyh",
		CreatorUserId = 2239168270
	},
	["HomeItem.Pixel Wardrobe"] = {
		CreatorName = "deNolD14",
		CreatorUserId = 304925488
	},
	["VehicleCustomization.Rim.DPad"] = {
		CreatorName = "NstMatt",
		CreatorUserId = 201573841
	},
	["VehicleCustomization.Rim.Python"] = {
		CreatorName = "Thomy3DA",
		CreatorUserId = 365246708
	},
	["HomeItem.Banana Chandelier"] = {
		CreatorName = "L2Wl5",
		CreatorUserId = 951428620
	},
	["VehicleCustomization.TireMesh.Jungle Ruins"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["VehicleCustomization.Drift.JungleVine"] = {
		CreatorName = "RealBlucube",
		CreatorUserId = 106812500
	},
	["VehicleCustomization.Spoiler.Snake Guard"] = {
		CreatorName = "Ne1lyh",
		CreatorUserId = 2239168270
	},
	["VehicleCustomization.Rim.Jungle Palm"] = {
		CreatorName = "Thomy3DA",
		CreatorUserId = 365246708
	},
	["VehicleCustomization.Texture.Snakeskin"] = {
		CreatorName = "Dr_Radium",
		CreatorUserId = 1308015890
	},
	["VehicleCustomization.Spoiler.Bamboo Shooters"] = {
		CreatorName = "Kunil_games",
		CreatorUserId = 1147296752
	},
	["Vehicle.Cobra"] = {
		CreatorName = "NstMatt",
		CreatorUserId = 201573841
	},
	["VehicleCustomization.TireMesh.ROK"] = {
		CreatorName = "Ne1lyh",
		CreatorUserId = 2239168270
	},
	["Vehicle.Expeditioner"] = {
		CreatorName = "Plasmazillah",
		CreatorUserId = 1009227115
	},
	["VehicleCustomization.Rim.Bamboo"] = {
		CreatorName = "MrYomelS",
		CreatorUserId = 1045693193
	},
	["VehicleCustomization.TireMesh.Safari"] = {
		CreatorName = "eggnog8483",
		CreatorUserId = 143494686
	},
	["VehicleCustomization.TireSticker.JungleMosaic"] = {
		CreatorName = "theogonn",
		CreatorUserId = 185302124
	},
	["VehicleCustomization.Texture.Prehistoric"] = {
		CreatorName = "Dr_Radium",
		CreatorUserId = 1308015890
	},
	["VehicleCustomization.Spoiler.Rally Lights"] = {
		CreatorName = "DrEzekielPlays",
		CreatorUserId = 2428138161
	},
	["HomeItem.Tiki Stack of Badimo"] = {
		CreatorName = "Dr_Radium",
		CreatorUserId = 1308015890
	},
	["HomeItem.Rally Signage"] = {
		CreatorName = "GhostRoblox76367",
		CreatorUserId = 1128590980
	},
	["VehicleCustomization.Drift.Bananas"] = {
		CreatorName = "OnionsAreEpic",
		CreatorUserId = 1168890974
	},
	["VehicleCustomization.Rim.Storm"] = {
		CreatorName = "GenjiTheGreater",
		CreatorUserId = 1735732063
	},
	["VehicleCustomization.TireSticker.Skull and Sails"] = {
		CreatorName = "i_m_FYRE",
		CreatorUserId = 3038531583
	},
	["VehicleCustomization.Rim.Kraken"] = {
		CreatorName = "happyhongo",
		CreatorUserId = 280742494
	},
	["VehicleCustomization.Spoiler.Yarg Cap"] = {
		CreatorName = "RealBlucube",
		CreatorUserId = 106812500
	},
	["HomeItem.Pirate Figurehead"] = {
		CreatorName = "angus23lego",
		CreatorUserId = 189121935
	},
	["VehicleCustomization.Rim.BrigBone"] = {
		CreatorName = "Dr_Radium",
		CreatorUserId = 1308015890
	},
	["VehicleCustomization.Drift.Oceanwater"] = {
		CreatorName = "sherrife15",
		CreatorUserId = 120624815
	},
	["VehicleCustomization.Texture.Buccaneer"] = {
		CreatorName = "Ocean1xs",
		CreatorUserId = 1302857292
	},
	["VehicleCustomization.Spoiler.Cannonfire"] = {
		CreatorName = "ShadowSamurai720",
		CreatorUserId = 391034465
	},
	["Vehicle.Blackbeard"] = {
		CreatorName = "Plasmazillah",
		CreatorUserId = 1009227115
	},
	["VehicleCustomization.Spoiler.Kraken Attack"] = {
		CreatorName = "Dr_Radium",
		CreatorUserId = 1308015890
	},
	["VehicleCustomization.Rim.TreasureIsland"] = {
		CreatorName = "Dr_Radium",
		CreatorUserId = 1308015890
	},
	["HomeItem.Captain Table"] = {
		CreatorName = "GhostRoblox76367",
		CreatorUserId = 1128590980
	},
	["HomeItem.Captain Chandelier"] = {
		CreatorName = "Dr_Radium",
		CreatorUserId = 1308015890
	},
	["HomeItem.Sloopwreck Bed"] = {
		CreatorName = "PyridiumWasTaken",
		CreatorUserId = 160813879
	},
	["VehicleCustomization.Spoiler.Dual WingBeat"] = {
		CreatorName = "Dune_Tune",
		CreatorUserId = 2436071685
	},
	["VehicleCustomization.Rim.147"] = {
		CreatorName = "XXXAnonimoTVXXX",
		CreatorUserId = 1094473683
	},
	["VehicleCustomization.Rim.Settima"] = {
		CreatorName = "XXXAnonimoTVXXX",
		CreatorUserId = 1094473683
	},
	["VehicleCustomization.Spoiler.Parrot"] = {
		CreatorName = "Ocean1xs",
		CreatorUserId = 1302857292
	},
	["Vehicle.OrionM42"] = {
		CreatorName = "Stealth_Llama",
		CreatorUserId = 424239986
	},
	["VehicleCustomization.TireMesh.MagmaticGlow"] = {
		CreatorName = "Kunil_games",
		CreatorUserId = 1147296752
	},
	["VehicleCustomization.Rim.P-100i"] = {
		CreatorName = "eggnog8483",
		CreatorUserId = 143494686
	},
	["VehicleCustomization.Spoiler.CyberPUNK"] = {
		CreatorName = "Dr_Radium",
		CreatorUserId = 1308015890
	},
	["HomeItem.Neon Vein Wall-Art"] = {
		CreatorName = "DrBaconBunny",
		CreatorUserId = 1821334335
	},
	["VehicleCustomization.Rim.Neo-Runner"] = {
		CreatorName = "Thomy3DA",
		CreatorUserId = 365246708
	},
	["VehicleCustomization.Spoiler.Stacked Cyberwing"] = {
		CreatorName = "Thomy3DA",
		CreatorUserId = 365246708
	},
	["VehicleCustomization.Drift.Neo-Static"] = {
		CreatorName = "sherrife15",
		CreatorUserId = 120624815
	},
	["VehicleCustomization.Texture.VibrantHologram"] = {
		CreatorName = "Ocean1xs",
		CreatorUserId = 1302857292
	},
	["VehicleCustomization.Rim.INF1N1TY"] = {
		CreatorName = "Ocean1xs",
		CreatorUserId = 1302857292
	},
	["Vehicle.Katana"] = {
		CreatorName = "Plasmazillah",
		CreatorUserId = 1009227115
	},
	["VehicleCustomization.TireSticker.Arch9000 Glow"] = {
		CreatorName = "Plasmazillah",
		CreatorUserId = 1009227115
	},
	["VehicleCustomization.Spoiler.Bleeding Edge"] = {
		CreatorName = "5TAGED",
		CreatorUserId = 7542749249
	},
	["VehicleCustomization.Spoiler.Voltline"] = {
		CreatorName = "SpeedQue3n",
		CreatorUserId = 2463010296
	},
	["VehicleCustomization.Rim.Hex-Bond"] = {
		CreatorName = "PyridiumWasTaken",
		CreatorUserId = 160813879
	},
	["VehicleCustomization.Rim.Armorpunk"] = {
		CreatorName = "Dr_Radium",
		CreatorUserId = 1308015890
	},
	["VehicleCustomization.Rim.Corp CR1"] = {
		CreatorName = "TOPrime1",
		CreatorUserId = 1367814618
	},
	["VehicleCustomization.TireSticker.Jade Glow"] = {
		CreatorName = "megaRaihany",
		CreatorUserId = 1248550182
	},
	["HomeItem.Hologram Donut Vendor"] = {
		CreatorName = "Dr_Radium",
		CreatorUserId = 1308015890
	},
	["HomeItem.Wanted Hologram Signage"] = {
		CreatorName = "wiphiax",
		CreatorUserId = 2502397118
	},
	["Vehicle.WYNDR"] = {
		CreatorName = "EyesOfObl1vion",
		CreatorUserId = 291914572
	},
	["VehicleCustomization.Texture.Katana"] = {
		CreatorName = "Plasmazillah",
		CreatorUserId = 1009227115
	},
	["VehicleCustomization.Texture.WYNDR"] = {
		CreatorName = "EyesOfObl1vion",
		CreatorUserId = 291914572
	},
	["VehicleCustomization.Texture.Cracky4JB"] = {
		CreatorName = "Dr_Radium",
		CreatorUserId = 1308015890
	},
	["VehicleCustomization.Spoiler.Roblox R"] = {
		CreatorName = "lolbob5551",
		CreatorUserId = 3122218552
	},
	["HomeItem.Avatar Wardrobe"] = {
		CreatorName = "SpeedQue3n",
		CreatorUserId = 2463010296
	},
	["VehicleCustomization.TireMesh.R2008"] = {
		CreatorName = "GCType11",
		CreatorUserId = 5022304440
	},
	["VehicleCustomization.Rim.Truss"] = {
		CreatorName = "SpeedQue3n",
		CreatorUserId = 2463010296
	},
	["HomeItem.Spawn Rug"] = {
		CreatorName = "tcein",
		CreatorUserId = 76533360
	},
	["VehicleCustomization.Drift.Bloxxer"] = {
		CreatorName = "Ocean1xs",
		CreatorUserId = 1302857292
	},
	["VehicleCustomization.Texture.RobloxStud"] = {
		CreatorName = "Ickleon37",
		CreatorUserId = 847255377
	},
	["VehicleCustomization.Spoiler.Bloxxer Launcher"] = {
		CreatorName = "Dune_Tune",
		CreatorUserId = 2436071685
	},
	["Vehicle.BrickKar"] = {
		CreatorName = "D4EAMER",
		CreatorUserId = 339428324
	},
	["VehicleCustomization.Rim.Speed Coil"] = {
		CreatorName = "King_Construction",
		CreatorUserId = 546559001
	},
	["VehicleCustomization.Spoiler.Classic Jet"] = {
		CreatorName = "GCType11",
		CreatorUserId = 5022304440
	},
	["Vehicle.PizzaDelivery"] = {
		CreatorName = "Dr_Radium",
		CreatorUserId = 1308015890
	},
	["VehicleCustomization.Rim.Spawn"] = {
		CreatorName = "ShadowSamurai720",
		CreatorUserId = 391034465
	},
	["VehicleCustomization.Drift.Subspace"] = {
		CreatorName = "sherrife15",
		CreatorUserId = 120624815
	},
	["VehicleCustomization.Rim.Animated Obby"] = {
		CreatorName = "megaRaihany",
		CreatorUserId = 1248550182
	},
	["VehicleCustomization.Rim.Delivery"] = {
		CreatorName = "XXXAnonimoTVXXX",
		CreatorUserId = 1094473683
	},
	["VehicleCustomization.TireSticker.SFOTH"] = {
		CreatorName = "Dune_Tune",
		CreatorUserId = 2436071685
	},
	["VehicleCustomization.TireMesh.Studded"] = {
		CreatorName = "lolaughvi",
		CreatorUserId = 547648615
	},
	["VehicleCustomization.Spoiler.BrickKar"] = {
		CreatorName = "D4EAMER",
		CreatorUserId = 339428324
	},
	["Vehicle.Bionic"] = {
		CreatorName = "eggnog8483",
		CreatorUserId = 143494686
	},
	["VehicleCustomization.Rim.Bad Omen"] = {
		CreatorName = "PlainMelvin",
		CreatorUserId = 1468428486
	},
	["VehicleCustomization.Rim.Scythes"] = {
		CreatorName = "DiamondKing",
		CreatorUserId = 83702035
	},
	["VehicleCustomization.Spoiler.Reaper"] = {
		CreatorName = "ItzTruminator",
		CreatorUserId = 996508101
	},
	["HomeItem.Haunting Door"] = {
		CreatorName = "TheGamingSquad_",
		CreatorUserId = 934409226
	},
	["VehicleCustomization.TireSticker.Thing"] = {
		CreatorName = "Yasaph",
		CreatorUserId = 1078791470
	},
	["VehicleCustomization.Spoiler.Ghost Catcher"] = {
		CreatorName = "DrBaconBunny",
		CreatorUserId = 1821334335
	},
	["VehicleCustomization.Texture.Chilling"] = {
		CreatorName = "pi_devv",
		CreatorUserId = 1712794135
	},
	["VehicleCustomization.Drift.Nemesis"] = {
		CreatorName = "megaRaihany",
		CreatorUserId = 1248550182
	},
	["Vehicle.BlackWidow"] = {
		CreatorName = "Plasmazillah",
		CreatorUserId = 1009227115
	},
	["VehicleCustomization.Spoiler.King Reaper"] = {
		CreatorName = "happyhongo",
		CreatorUserId = 280742494
	},
	["VehicleCustomization.Texture.BlackWidow"] = {
		CreatorName = "Plasmazillah",
		CreatorUserId = 1009227115
	},
	["Vehicle.Polaire"] = {
		CreatorName = "Phindr",
		CreatorUserId = 76393113
	},
	["VehicleCustomization.Texture.PolaireCamo"] = {
		CreatorName = "Phindr",
		CreatorUserId = 76393113
	},
	["VehicleCustomization.Texture.RunNGun"] = {
		CreatorName = "gloreo_m",
		CreatorUserId = 162133508
	},
	["VehicleCustomization.TireMesh.RadialRed"] = {
		CreatorName = "TheGamingSquad_",
		CreatorUserId = 934409226
	},
	["HomeItem.Rest In Peace"] = {
		CreatorName = "ArdaSenYb",
		CreatorUserId = 1600624028
	},
	["HomeItem.Scary Organ"] = {
		CreatorName = "DrEzekielPlays",
		CreatorUserId = 2428138161
	},
	["HomeItem.Scary Sofa"] = {
		CreatorName = "ArdaSenYb",
		CreatorUserId = 1600624028
	},
	["HomeItem.Scary Treasures"] = {
		CreatorName = "Dr_Radium",
		CreatorUserId = 1308015890
	},
	["HomeItem.Trapped Spikes"] = {
		CreatorName = "ShadowSamurai720",
		CreatorUserId = 391034465
	},
	["VehicleCustomization.Rim.Lapine"] = {
		CreatorName = "Phindr",
		CreatorUserId = 76393113
	},
	["VehicleCustomization.Rim.Theory"] = {
		CreatorName = "IkaLikesMemez",
		CreatorUserId = 1496118636
	},
	["VehicleCustomization.TireMesh.Voltline"] = {
		CreatorName = "Thomy3DA",
		CreatorUserId = 365246708
	},
	["VehicleCustomization.TireSticker.Freestyle"] = {
		CreatorName = "theogonn",
		CreatorUserId = 185302124
	},
	["VehicleCustomization.Rim.Quicksilver"] = {
		CreatorName = "Phindr",
		CreatorUserId = 76393113
	},
	["VehicleCustomization.Spoiler.Skyline"] = {
		CreatorName = "TheGamingSquad_",
		CreatorUserId = 934409226
	},
	["VehicleCustomization.Drift.DarkMatter"] = {
		CreatorName = "Ocean1xs",
		CreatorUserId = 1302857292
	},
	["VehicleCustomization.Texture.DigitalRGB"] = {
		CreatorName = "Poogah",
		CreatorUserId = 2267756092
	},
	["VehicleCustomization.Spoiler.MetalStinger"] = {
		CreatorName = "MazeGFX",
		CreatorUserId = 125083697
	},
	["Vehicle.JBX0031"] = {
		CreatorName = "Axaraz",
		CreatorUserId = 243536285
	},
	["VehicleCustomization.Spoiler.Holo"] = {
		CreatorName = "Kunil_games",
		CreatorUserId = 1147296752
	},
	["VehicleCustomization.Texture.JBX0031"] = {
		CreatorName = "Axaraz",
		CreatorUserId = 243536285
	},
	["Vehicle.Bluebird"] = {
		CreatorName = "Phindr",
		CreatorUserId = 76393113
	},
	["VehicleCustomization.Spoiler.Cassette"] = {
		CreatorName = "SwarmerXXXL",
		CreatorUserId = 1234289052
	},
	["VehicleCustomization.Drift.Rainboom"] = {
		CreatorName = "RealBlucube",
		CreatorUserId = 106812500
	},
	["VehicleCustomization.Spoiler.SuperAttack"] = {
		CreatorName = "GCType11",
		CreatorUserId = 5022304440
	},
	["VehicleCustomization.TireMesh.ClosedCircuit"] = {
		CreatorName = "DydyWasTaken",
		CreatorUserId = 591295581
	},
	["HomeItem.Crazy Driver"] = {
		CreatorName = "YourLocalBloxydealer",
		CreatorUserId = 3100533570
	},
	["VehicleCustomization.Rim.MonsterVoid"] = {
		CreatorName = "SpeedQue3n",
		CreatorUserId = 2463010296
	},
	["VehicleCustomization.Rim.Aeroblob"] = {
		CreatorName = "DrEzekielPlays",
		CreatorUserId = 2428138161
	},
	["VehicleCustomization.Texture.Bluebird"] = {
		CreatorName = "Phindr",
		CreatorUserId = 76393113
	},
	["VehicleCustomization.Spoiler.Birdtail"] = {
		CreatorName = "Phindr",
		CreatorUserId = 76393113
	},
	["HomeItem.BunnyBed"] = {
		CreatorName = "Plasmazillah",
		CreatorUserId = 1009227115
	}
}
