-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMMBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZAZCaW5kZXIQSG90YmFySXRlbUNvbnN0cwZzY3JpcHQGUGFyZW50A25ldwhUQUdfTkFNRQpIb3RiYXJJdGVtAAEIAAABAgAmowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQIAoQYAAABNAgJ/BwAAAJ8BAgKkAgUAAABAQKQECgAAAJBATQQEJAsAAABNAwRrCAAAAJ8CAgJNAwHvDAAAAE0EArQNAAAApAUFAAAAQECkBwoAAACQQE0HByQLAAAATQYHaw4AAACfBQIAnwMAAIIDAAAPAwEEAAAAQAMCAwMDBAQAAEBAAwUDBgMHAwgEAACQQAMJAwoDCwMMAAEAARgAAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAEAAAAAANLuDopshPdpvmHxtYBTMx6i9hn+4Cpkiw==

-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2026-04-18 23:43:29
-- Luau version 6, Types version 3
-- Time taken: 0.000685 seconds

return require(game:GetService("ReplicatedStorage").Std.Binder).new(require(script.Parent.HotbarItemConsts).TAG_NAME, require(script.Parent.HotbarItem))