-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMGBVN0YXJ0BGluaXQHcmVxdWlyZQZzY3JpcHQGUGFyZW50F1RyYWNraW5nU3BvdGxpZ2h0QmluZGVyAAICAAEAAAAF+wAAALwAABwAAAAAnwACAYIAAQABAwEAAwIBGAAAAAABBAAAAAADAAABAgARowAAAKQAAQAAAABApAEDAAAAIEBNAQEkBAAAAE0BAQoFAAAAnwACAv8BAQAAAAAAwAIGABIAAAAwAgETBwAAAIIBAgAIAwMEAAAAQAMEBAAAIEADBQMGBgADAgEAAQABGAAAAAAAAAAAAAABAAEAAAADAQAAAAAB

-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2026-04-18 23:47:08
-- Luau version 6, Types version 3
-- Time taken: 0.000636 seconds

local module = {}
local TrackingSpotlightBinder_upvr = require(script.Parent.TrackingSpotlightBinder)
function module.init() -- Line 3
    --[[ Upvalues[1]:
        [1]: TrackingSpotlightBinder_upvr (readonly)
    ]]
    TrackingSpotlightBinder_upvr:Start()
end
return module