-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMMBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZAZCaW5kZXIUTWlsaXRhcnlUdXJyZXRDb25zdHMGc2NyaXB0BlBhcmVudANuZXcIVEFHX05BTUUOTWlsaXRhcnlUdXJyZXQAAQgAAAECACajAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAgChBgAAAE0CAn8HAAAAnwECAqQCBQAAAEBApAQKAAAAkEBNBAQkCwAAAE0DBGMIAAAAnwICAk0DAe8MAAAATQQCtA0AAACkBQUAAABAQKQHCgAAAJBATQcHJAsAAABNBgfsDgAAAJ8FAgCfAwAAggMAAA8DAQQAAABAAwIDAwMEBAAAQEADBQMGAwcDCAQAAJBAAwkDCgMLAwwAAQABGAAAAAAAAAABAAAAAAAAAQAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAQAAAAAAwJkTz+rrB0oUcj66s+NfSbCBBLvyXXnO

-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2026-04-18 23:38:16
-- Luau version 6, Types version 3
-- Time taken: 0.000574 seconds

return require(game:GetService("ReplicatedStorage").Std.Binder).new(require(script.Parent.MilitaryTurretConsts).TAG_NAME, require(script.Parent.MilitaryTurret))