-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMGBVN0YXJ0BGluaXQHcmVxdWlyZQ1TdXJmYWNlQmluZGVyBnNjcmlwdAZQYXJlbnQAAgIAAQAAAAX7AAAAvAAAHAAAAACfAAIBggABAAEDAQAEAgEYAAAAAAEFAAAAAAMAAAECABGjAAAApAABAAAAAECkAgQAAAAwQE0CAiQFAAAATQECPwIAAACfAAIC/wEBAAAAAADAAgYAEgAAADACARMHAAAAggECAAgDAwQAAABAAwQDBQQAADBAAwYGAAMCAQABAAEYAAAAAAAAAAAAAAIAAQAAAAMBAAAAAAE=

-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2026-04-18 23:43:21
-- Luau version 6, Types version 3
-- Time taken: 0.000646 seconds

local module = {}
local SurfaceBinder_upvr = require(script.Parent.SurfaceBinder)
function module.init() -- Line 4
    --[[ Upvalues[1]:
        [1]: SurfaceBinder_upvr (readonly)
    ]]
    SurfaceBinder_upvr:Start()
end
return module