-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMIBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlA1N0ZApUYWJsZVV0aWxzGnJlcXVpcmVWYWxpZEluZGV4QW5kRnJlZXplFkZSSUVORF9VUERBVEVfSU5URVJWQUwAAQUAAAECABajAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAgChBgAAAE0CAhgHAAAAnwECAk0CAQAIAAAA4gMKAIwEWAIwBAMsCQAAAJ8CAgCCAgAACwMBBAAAAEADAgMDAwQEAABAQAMFAwYDBwMIBQEJAAEAARgAAAAAAAAAAQAAAAAAAAEAAAEAAP8AAQAAAAAAEq83ka6YrA9zv6e1cEE2pWK3IOUga12Q

-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2026-04-18 23:42:00
-- Luau version 6, Types version 3
-- Time taken: 0.000408 seconds

return require(game:GetService("ReplicatedStorage").Std.TableUtils).requireValidIndexAndFreeze({
    FRIEND_UPDATE_INTERVAL = 600;
})