-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMCBVNwZWVkEUdhcmFnZUVuZ2luZVNwZWVkAAIDAgAAAAAKDgAFAE0CACwAAAAAMAIBrwEAAACCAAEAjAIAADACAa8BAAAAggABAAIDAQMCAAIAARgAAQAAAAACAAACAwAAAAABAAABAgADowAAAMAAAACCAAIAAQYAAQABAAEYAAEAAQAAAAABKPnx65O8CqQaPZt/FZ5eG4caeguagEJ5gCrprDLpCGnXVaCELz3QTw==

return function(v0, v1) --[[ Line: 2 ]]
    if v0 then
        v1.GarageEngineSpeed = v0.Speed;
        return;
    else
        v1.GarageEngineSpeed = 0;
        return;
    end;
end;