-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMEBVRpdGxlBVNvbmdzCUNsYXNzaWNhbAdBc3NldElkAAENAAABAgA0owAAAOIAAgBvAQMAMAEAugAAAAD/AQAACgAAAOICBQBvAwYAMAMCiQQAAADiAwUAbwQHADAEA4kEAAAA4gQFAG8FCAAwBQSJBAAAAOIFBQBvBgkAMAYFiQQAAADiBgUAbwcKADAHBokEAAAA4gcFAG8ICwAwCAeJBAAAAOIIBQBvCQwAMAkIiQQAAADiCQUAbwoNADAKCYkEAAAA4goFAG8LDgAwCwqJBAAAAOILBQBvDA8AMAwLiQQAAADFAQILAQAAADABAN8BAAAAggACABADAQMCBQIAAQMDAwQFAQQCAACAQ5Zr20ECAABIW1vZAEICAAAA2MqJ20ECAADAf25720ECAAAANj9z20ECAABAStxc20ECAACIUsfZAEICAACAu2th20ECAADA8MOJ20ECAACAa8KJ20EAAQABGAAAAQAAAQABAQAAAgEAAAIBAAACAQAAAgEAAAIBAAACAQAAAgEAAAIBAAACAQAAAADjAAABAAAAAACACEXNkUqzHkhV1Vl3qIjj8BBSubLML8w=

-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2026-04-18 23:38:43
-- Luau version 6, Types version 3
-- Time taken: 0.001204 seconds

return {
    Title = "Classical";
    Songs = {{
        AssetId = 1840142606;
    }, {
        AssetId = 9045764969;
    }, {
        AssetId = 1848060768;
    }, {
        AssetId = 1844296191;
    }, {
        AssetId = 1842150616;
    }, {
        AssetId = 1836282153;
    }, {
        AssetId = 9046649425;
    }, {
        AssetId = 1837477614;
    }, {
        AssetId = 1848053699;
    }, {
        AssetId = 1848052142;
    }};
}