return {
	Title = "LawnReality",
	Songs = {
		{
			Name = "First Snowfall",
			AssetId = 138525035364893
		},
		{
			Name = "2024 Track1",
			AssetId = 17046617226
		},
		{
			Name = "2024 Track2",
			AssetId = 17046620172
		},
		{
			Name = "2024 Track3",
			AssetId = 17046629351
		},
		{
			Name = "2024 Track4",
			AssetId = 17046627090
		},
		{
			Name = "Spectrum",
			AssetId = 9063004589
		},
		{
			Name = "Safehouse",
			AssetId = 9063115823
		},
		{
			Name = "Doing Well",
			AssetId = 5411347344
		},
		{
			Name = "Hoverbike Escape",
			AssetId = 9062888789
		},
		{
			Name = "Night",
			AssetId = 5411346383
		},
		{
			Name = "Living Dream",
			AssetId = 5411345631
		},
		{
			Name = "Cold Nights",
			AssetId = 9062904818
		},
		{
			Name = "Lonely Voyage",
			AssetId = 9062913444
		},
		{
			Name = "Summer Nights",
			AssetId = 9062922824
		},
		{
			Name = "The Passage of Time",
			AssetId = 9062937002
		},
		{
			Name = "The Day\'s Beginning",
			AssetId = 9062946210
		},
		{
			Name = "A Night Away",
			AssetId = 5411340544
		},
		{
			Name = "Awakening Moonlight",
			AssetId = 9062955202
		},
		{
			Name = "The Champion",
			AssetId = 5411339477
		}
	}
}